//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMBB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMBB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRSTM has created successfully.
        /// </summary>
        public static string BrstmBuildSucceed {
            get {
                return ResourceManager.GetString("BrstmBuildSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string BuildStartLabel {
            get {
                return ResourceManager.GetString("BuildStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels:.
        /// </summary>
        public static string ChannelLabel {
            get {
                return ResourceManager.GetString("ChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path:.
        /// </summary>
        public static string DestinationLabel {
            get {
                return ResourceManager.GetString("DestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorCapacity {
            get {
                return ResourceManager.GetString("ErrorCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occurred while spliting audio file.
        /// </summary>
        public static string FailedAudioSplitAlert {
            get {
                return ResourceManager.GetString("FailedAudioSplitAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occurred while building BRSTM.
        /// </summary>
        public static string FailedBrstmBuildAlert {
            get {
                return ResourceManager.GetString("FailedBrstmBuildAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occurred in DSPADPCM process.
        /// </summary>
        public static string FailedDspadpcmProcessAlert {
            get {
                return ResourceManager.GetString("FailedDspadpcmProcessAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Setting File.
        /// </summary>
        public static string FiletypeLoopSetting {
            get {
                return ResourceManager.GetString("FiletypeLoopSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files.
        /// </summary>
        public static string FiletypeSpecifiedInput {
            get {
                return ResourceManager.GetString("FiletypeSpecifiedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRSTM File.
        /// </summary>
        public static string FiletypeSpecifiedOutput {
            get {
                return ResourceManager.GetString("FiletypeSpecifiedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build as Final Lap Stream.
        /// </summary>
        public static string FinalLapBuildLabel {
            get {
                return ResourceManager.GetString("FinalLapBuildLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Path:.
        /// </summary>
        public static string ImportAudioLabel {
            get {
                return ResourceManager.GetString("ImportAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file because it&apos;s invalid.
        /// </summary>
        public static string InvalidFileAlert {
            get {
                return ResourceManager.GetString("InvalidFileAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Setting.
        /// </summary>
        public static string LoadLoopSettingLabel {
            get {
                return ResourceManager.GetString("LoadLoopSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fix loop end point automatically.\nDue to trying to fix loop end point,\nthe value of Loop End Sample has set later than source.\nWould you like to create BRSTM without loop end point auto-fix?.
        /// </summary>
        public static string LoopEndFixCaution {
            get {
                return ResourceManager.GetString("LoopEndFixCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Loop End Sample is larger than source.
        /// </summary>
        public static string LoopEndOverSourceWarning {
            get {
                return ResourceManager.GetString("LoopEndOverSourceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop End Sample:.
        /// </summary>
        public static string LoopEndValueLabel {
            get {
                return ResourceManager.GetString("LoopEndValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Settings.
        /// </summary>
        public static string LoopSettingAreaLabel {
            get {
                return ResourceManager.GetString("LoopSettingAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Loop Start is set later than Loop End.
        /// </summary>
        public static string LoopStartAfterEndWarning {
            get {
                return ResourceManager.GetString("LoopStartAfterEndWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Start Sample:.
        /// </summary>
        public static string LoopStartValueLabel {
            get {
                return ResourceManager.GetString("LoopStartValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string LoopToggleLabel {
            get {
                return ResourceManager.GetString("LoopToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Loop Values are set at same position.
        /// </summary>
        public static string LoopValuesSameWarning {
            get {
                return ResourceManager.GetString("LoopValuesSameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed files not found. Make sure &apos;tools&apos; folder contains files as following:\n.
        /// </summary>
        public static string NonToolsAlert {
            get {
                return ResourceManager.GetString("NonToolsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building BRSTM....
        /// </summary>
        public static string ProgressBrstmBuild {
            get {
                return ResourceManager.GetString("ProgressBrstmBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding DSPADPCM....
        /// </summary>
        public static string ProgressDspadpcmEncode {
            get {
                return ResourceManager.GetString("ProgressDspadpcmEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting channels....
        /// </summary>
        public static string ProgressWaveSplit {
            get {
                return ResourceManager.GetString("ProgressWaveSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to samples.
        /// </summary>
        public static string SampleUnit {
            get {
                return ResourceManager.GetString("SampleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Setting.
        /// </summary>
        public static string SaveLoopSettingLabel {
            get {
                return ResourceManager.GetString("SaveLoopSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create tmp folder.
        /// </summary>
        public static string TempFolderFailedAlert {
            get {
                return ResourceManager.GetString("TempFolderFailedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file due to error occurring.
        /// </summary>
        public static string UnableOpenFileAlert {
            get {
                return ResourceManager.GetString("UnableOpenFileAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the file due to invalid or unsupported format.
        /// </summary>
        public static string UnableReadAudioAlert {
            get {
                return ResourceManager.GetString("UnableReadAudioAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file due to error occurring.
        /// </summary>
        public static string UnableSaveFileAlert {
            get {
                return ResourceManager.GetString("UnableSaveFileAlert", resourceCulture);
            }
        }
    }
}
